#+title: system

#+begin_quote
A system is a group of interacting or interrelated entities that act according to a set of rules to form a unified whole. A system, surrounded and influenced by its environment, is described by its spatiotemporal boundaries, structure, and purpose and expressed in its functioning.

―[[https://en.wikipedia.org/wiki/System][Wikipedia]], the free encyclopedia
#+end_quote

This repository houses my system configuration, comprising the configs of software I use as well as the OS-level configs of the computers I operate. To manage it all, I use [[https://nixos.org/][NixOS]], a Linux distribution based on the Nix package manager focusing on reproducible builds and environments.

Like just about any other dotfiles repo, this one isn't really designed to be used as-is. Unfortunately, I still maintain a private runbook documenting imperative setup I haven't fully exorcised, and portions of configurations reference data I don't publish. I've made the rest public because NixOS configurations weren't very common when I got started and so I could more easily get advice from other users. If you have a question or suggestion, feel free to reach out.
