#!/bin/sh
alias pk="pkill" \
	mkd="mkdir -pv" \
	mpv='mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)' \
	nrs="sudo nixos-rebuild switch" \
	nrb="sudo nixos-rebuild boot" \
	nrt="sudo nixos-rebuild test" \
	hms="home-manager switch" \
	SS="sudo systemctl" \
	dots='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME' \
	f='$FILE' \
	trem="transmission-remote" \
	e='$EDITOR' \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.
